### ISSUE TITLE
[bug] backend apps: "ReferenceError: XMLHttpRequest is not defined"

### ISSUE THREAD

**Issue by remon-nashid** [PolymathNetwork/polymath-sdk#105]
It seems that the SDK assumes a browser environment because I get this error on Node.js. 

```
ReferenceError: XMLHttpRequest is not defined
    at Object.<anonymous> (/Users/remon/projects/sdk-sandbox/node_modules/@polymathnetwork/sdk/dist/index.js:21:140249)
```

To reproduce the issue, just create a vanilla node.js project, add polymath-sdk, and then run the following js snippet:

```
const { Polymath } = require('@polymathnetwork/sdk');
```

**Comment by monitz87** [comment]
I had this issue at some point, and made it so that the SDK distributes two different bundles (one for the browser and one for node)

I tried this just now (beta.46) running the snippet with `node test.js` and everything worked fine.

**Comment by VictorVicente** [comment]
I tried too and it worked without problems, could you test it again @remon-nashid?

**Comment by remon-nashid** [comment]
Works now. Thanks
