### ISSUE TITLE
[bug] permissions.assignRole throws an error

### ISSUE THREAD

**Issue by remon-nashid** [PolymathNetwork/polymath-sdk#107]
I'm trying to assign a role as follows:
```
const token = (await sdk.getSecurityToken({ symbol: 'RN' }))[0]
const q = await token.permissions.assignRole({symbol: "RN", assign: true, delegateAddress: "0x1B2D2797A56c9eBa12aa821D643aB0dBa66C3772", role: "PermissionsAdministrator"})
await q.run()
```
But it throws this unhelpful error:

```
index.js:1375 TypeError: Cannot read property 'length' of undefined
    at t.<anonymous> (index.browser.js:38555)
    at index.browser.js:38448
    at Object.next (index.browser.js:38460)
    at o (index.browser.js:38350)
```

**Comment by monitz87** [comment]
In stand-by until a reproducible example is supplied (the current one was built from memory and doesn't reproduce the error)

**Comment by remon-nashid** [comment]
@monitz87 try this:

```
const { Polymath } = require('@polymathnetwork/sdk');

(async function() {

  const privateKey = 'PRIV_KEY';
  const networkId = 42;
  const symbol = 'SYMBOL'

  const feature = 'Permissions'
  const role = 'ShareholdersAdministrator'
  const delegateAddress = '0xDELEGATE_ADDRESS'

  const networkConfigs = {
    1: {
      polymathRegistryAddress: '0xdfabf3e4793cd30affb47ab6fa4cf4eef26bbc27',
      providerUrl: 'https://mainnet.polymath.network',
      privateKey
    },
    42: {
      polymathRegistryAddress: '0x5b215a7d39ee305ad28da29bf2f0425c6c2a00b3',
      providerUrl: 'https://kovan.polymath.network',
      privateKey
    },
  };
  const config = networkConfigs[networkId];
  const sdk = new Polymath();
  await sdk.connect(config);

  try {
    const token = await sdk.getSecurityToken({symbol});
    const enabled = await token.features.isEnabled({feature})
    if (enabled) {
      console.log('GTM is enabled')
      const q = await token.permissions.assignRole({delegateAddress, role, description: 'test'})
      const ret = await q.run()
    }
  } catch(error) {
    console.error(error);
  }
})();
```

**Comment by remon-nashid** [comment]
Can't reproduce it on latest SDK beta.

**Comment by remon-nashid** [comment]
I'm getting this error again with beta 50, but it might be reproducible with earlier versions. Please see the attached screenshot bellow. 

To reproduce:

- Go to https://polymathnetwork.github.io/permissions/
- Select a token.
- Click on 'assign a role'
- Fill all fields then click submit.

The transaction in question is here https://github.com/PolymathNetwork/permissions/blob/master/src/App.js#L272

<img width="1381" alt="Screen Shot 2019-11-14 at 2 44 19 PM" src="https://user-images.githubusercontent.com/1994818/68902611-a85e7580-06ed-11ea-8b46-98f1c50bbc48.png">

**Comment by monitz87** [comment]
I need a minimal reproducible example with just SDK code. Also, I can't get to that part of the dApp, I get `invalid bytes32 string - no null terminator` when I select a token.

**Comment by remon-nashid** [comment]
Well I'm trying to write you a Node.js example but I keep getting `ReferenceError: XMLHttpRequest is not defined`

**Comment by remon-nashid** [comment]
@monitz87 I found another clue. The error above occurs when one attempts to assign a role, to a _new_ delegate that hasn't been added before. If I add a delegate using Token Studio or any other method, then attempt to `assignRole` to them, it works fine. 
BTW the code sample above still applies.

**Comment by remon-nashid** [comment]
> Also, I can't get to that part of the dApp, I get invalid bytes32 string - no null terminator when I select a token.

That was probably a 2.x token.

**Comment by VictorVicente** [comment]
It's working fine for me. 
Running the following script:
`import { Polymath, TransactionSpeed, Feature, SecurityTokenRole } from './src';

(async () => {
  const polyClient = new Polymath();

  await polyClient.connect({
    polymathRegistryAddress: '0x7E5A59E2Db8977d288bcf3225d4018f7b373cF8b',
    providerUrl: 'http://127.0.0.1:8545',
    privateKey: 'xxx',
    speed: TransactionSpeed.Fastest,
  });

  const mySecurityToken = await polyClient.getSecurityToken({ symbol: 'TEST' });

  const isPermEnabled = await mySecurityToken.features.isEnabled({ feature: Feature.Permissions });
  console.log('isPermEnabled:', isPermEnabled);
  if (!isPermEnabled) {
    await (await mySecurityToken.features.enable({ feature: Feature.Permissions })).run();
  }

  await (await mySecurityToken.permissions.assignRole({
    delegateAddress: '0xbfd02b95a0ba36807902d1c31b66edae90ec2151',
    role: SecurityTokenRole.ShareholdersAdministrator,
    description: 'test',
  })).run();

  const delegates = await mySecurityToken.permissions.getAllDelegates();
  console.log('delegates:', delegates);
})().catch(err => console.log(err));`

The first time it adds the delegate and it assigns the permission smoothly. The second time it runs, it fails due the permission is already assigned.

**Comment by remon-nashid** [comment]
@VictorVicente do you mind trying that same script on a new token and on Kovan network?

**Comment by VictorVicente** [comment]
The same script worked on a fresh token on Kovan network. If you try this script, is it showing the same error you described?

**Comment by remon-nashid** [comment]
I guess I have ghosts 👻
