### ISSUE TITLE
[bug] token.mintTokens : date(s) validation returns a generic error message   

### ISSUE THREAD

**Issue by remon-nashid** [PolymathNetwork/polymath-sdk#123]
Attempting to mint to a shareholder that has a valid KYC record (hasn't expired yet) might fail validation because said shareholder cannot receive, yet. However the error in this case reads:

```
Cannot mint tokens to the following addresses: [0x1b2d2797a56c9eba12aa821d643ab0dba66c3772]. Reason: Expired KYC
```

**Comment by VictorVicente** [comment]
You're right, we'll fix that! Thank you

**Comment by remon-nashid** [comment]
One more thing @VictorVicente, besides the mislabelled validation field (kycExpiry vs canReceiveAfter), I believe sdk validation is too restrictive. Basically it's preventing minting to aninvestor that cannot buy until a future date, which is a bug, because they should still be able to receive issuance.

**Comment by VictorVicente** [comment]
Yes, we're refactoring all that part to avoid this kind of problems. Thanks!
