### ISSUE TITLE
[feature] add ST.shareholders.redeem (or burn)

### ISSUE THREAD

**Issue by remon-nashid** [PolymathNetwork/polymath-sdk#130]

**Comment by VictorVicente** [comment]
As it stands today the only mechanism for reducing token supply is for the issuer/owner of the token to assign a controller, who then can call controllerRedeem on the token.
The issuer can not burn tokens directly, and a tokenholder can't do it on their own (reasoning for that back then was that it was weird that tokenholders could reduce supply of a security on their own)
Of course the issuer can add their own address as controller so they can actually do this.

**Comment by remon-nashid** [comment]
@VictorVicente but we're still implementing a `token.controller` feature, right?
