### ISSUE TITLE
is it any possibility to sign transactions on backend side? 

### ISSUE THREAD

**Issue by glorymlory** [PolymathNetwork/polymath-sdk#168]

**Comment by VictorVicente** [comment]
Hey @glorymlory, I'm not sure what you mean.
If you want to sign transactions without Metamask plugin, yes, it's possible. 
When you call to `connect` you could use different types of providers. Please check our examples at readme in `polymath-contract-wrappers` repository using them.
https://github.com/PolymathNetwork/polymath-contract-wrappers

Was this what you need?
