### ISSUE TITLE
[feature] add a function that retrieves tokens owned by a given address

### ISSUE THREAD

**Issue by remon-nashid** [PolymathNetwork/polymath-sdk#57]
~Bonus: also retrieve tokens that the given address is permitted to ADMIN.~ This will be quite tricky, as permissions are configured per module rather that the entire token.

**Comment by monitz87** [comment]
#56 adds `getSecurityTokens({ owner: string })` which returns all STs owned by an address. The second part hasn't been implemented yet

**Comment by remon-nashid** [comment]
Thanks @monitz87 !
