### ISSUE TITLE
[improvement] SecurityToken entity: add "version" property

### ISSUE THREAD

**Issue by remon-nashid** [PolymathNetwork/polymath-sdk#65]
**Bonus**: allow filtering tokens by version, e.g `polyClient.getSecurityTokens({owner: address, version: '3.0.0'})`

**Comment by VictorVicente** [comment]
One of the pending tasks is to add all the properties to the SecurityToken entity (name, details, granularity, divisible, version, etc). This will cover this issue.
For the bonus, let us think which is the best option there. It's a nice to have feature but you could do that easily filtering all the results after they were fetched, so I don't know if it worth it.

**Comment by remon-nashid** [comment]
> you could do that easily filtering all the results after they were fetched, so I don't know if it worth it.

Sure, fetched tokens can be filtered, so this is definitely not an impediment. But something worth mentioning is that, loading many tokens (even more than a couple) can take a decent amount of time. You can get a taste of that by visiting the app below, and login to a metamask account that happens to own many tokens on the current network. 

For that reason filtering would still be quite beneficial. Perhaps later we can batch smart contract calls together using Web3 `BatchRequest`. https://web3js.readthedocs.io/en/v1.2.0/web3-eth.html#batchrequest

**Comment by VictorVicente** [comment]
Version is now included as part of ST properties. Made in #144
