### ISSUE TITLE
[bug] Gas price is too low

### ISSUE THREAD

**Issue by remon-nashid** [PolymathNetwork/polymath-sdk#66]
The default gas price for transactions (at least modifyKYCData) is too low. As you can see in the screenshot below, the price is `1 Gwei`. So far that transaction hasn't confirmed yet. In another instance, the transaction just reverted because `transaction priced too low`.

Note that the issue is passable on Kovan, but it becomes an impediment on mainnet.

Please let me know if this is rather an issue of the contract wrappers.

<img width="814" alt="Screen Shot 2019-08-21 at 8 33 39 AM" src="https://user-images.githubusercontent.com/1994818/63432248-d2eeaa00-c3ee-11e9-83fd-e1a835841891.png">

**Comment by VictorVicente** [comment]
The default gasPrice can be overran when wrappers are created. 
@monitz87 could we expose this feature on the SDK? Also it would be great if we could fetch the default value from somewhere.

**Comment by remon-nashid** [comment]
Perhaps [web3.eth.getGasPrice()](https://web3js.readthedocs.io/en/v1.2.0/web3-eth.html#getgasprice) could help with the default value?
