### ISSUE TITLE
[feature] ST.shareholders: allow deleting a shareholder

### ISSUE THREAD

**Issue by remon-nashid** [PolymathNetwork/polymath-sdk#67]
I assumed, naively, that one can delete a shareholder from GTM's whitelist, by setting all values to `0` as it's usually done in solidity. However, I got an exception because the SDK (or the wrappers) are expecting Date objects:

```
const queue = await someToken.shareholders.modifyData({shareholderData:
  [{
      address: '0x592E80AD45c08aba6C5bBd2d5C5A097BDF35Dee1',
      canReceiveAfter: 0,
      canSendAfter: 0,
      kycExpiry: 0,
      isAccredited: 0,
      canBuyFromSto: 0
  }]
})
queue.run();

// Exception:
Uncaught (in promise) TypeError: e.getTime is not a function
```

Perhaps we need a completely different function for deleting shareholders (e.g `token.shareholders.delete({shareholdersData}`), then that function will call `modifyKYCDagta` and `modifyInvestorFlags` while passing zeros.

I believe `delete` operation will be needed for many other modules besides the GTM (e.g GPM).

**Comment by VictorVicente** [comment]
You are right, that seems to be the right approach for the GTM. We should implement a delete method.
On the other hand, GPM module has methods to delete delegates specifically, no other module comes to my mind with these type of requirements.

**Comment by remon-nashid** [comment]
I'm not sure if this warrants a different issue. I found that revoked Kyc entries, would still be returned in a following call to`getShareholders`, with dates set to epoch. 

Is that the intended behaviour? 

<img width="1343" alt="Screen Shot 2019-08-29 at 5 44 55 AM" src="https://user-images.githubusercontent.com/1994818/63929866-30eb4500-ca20-11e9-828f-c97d2a2d5b94.png">

**Comment by remon-nashid** [comment]
While the KYC record in question has certainly expired, it's not technically deleted. Maybe we need to pass `0` integers to the following call, instead of `Date(0)`?

https://github.com/PolymathNetwork/polymath-sdk/blob/beta/src/procedures/RevokeKyc.ts#L70

**Comment by VictorVicente** [comment]
Even when `Date(0)` is sent to the wrappers, behind the scenes this value is converted to a simple 0 when it is sent to the contracts, so it's the same.

The shareholder is appearing because the contract is returning it. The contract will return any investor who had balance or KYC data at least once. 
To solve this we are going to filter it from on our SDK.
We will return only those shareholders fulfilling any of these requirements:
- Balance != 0
- Any KYC date != 0
- Any flag != 0

**Comment by remon-nashid** [comment]
Tried again on `beta-29`, I get that error upon calling `revokeKyc`:

```
RevokeKyc.js:82 Uncaught (in promise) TypeError: shareholder.isRevoked is not a function
    at RevokeKyc.js:82
    at Array.filter (<anonymous>)
    at RevokeKyc.<anonymous> (RevokeKyc.js:82)
    at Generator.next (<anonymous>)
    at fulfilled (RevokeKyc.js:7)
```
