### ISSUE TITLE
[feature] Polymath.connect() to accept private key or mnemonics

### ISSUE THREAD

**Issue by remon-nashid** [PolymathNetwork/polymath-sdk#70]
Otherwise, the SDK could only be used either with Metamask, or a local, permenantly unlocked `geth` or `parity` nodes.

**Comment by VictorVicente** [comment]
This is already implemented. The `connect` method has an overload which requires a provider url and a privateKey. 
This way let us use it as you said, with any other remote node. 
The providers logic on our contract-wrappers allow us to offer different more alternatives in the future but currently both you mentioned are working.

**Comment by remon-nashid** [comment]
Thanks @VictorVicente. I have no idea how I overlooked that.
